### ISSUE TITLE
Gitnow@2.3.0 add unwanted entries into kubens and kubectx

### ISSUE THREAD

**Issue by erismaster** [joseluisq/gitnow#12]
After updating to 2.3.0, I noticed that I started seeing the following entries in kubens and kubectx (with fzf)

`GitNow: Configured and ready to use!`
`GitNow: Downloading default configuration file...`

If I downgrade back to 2.2.0 I do not see these entries. Fzf itself is not getting these extra GitNow entries; I've only noticed it with kubectx and kubens.

**Comment by joseluisq** [comment]
Yep, It was due https://github.com/joseluisq/gitnow/blob/2.3.0/functions/__gitnow_config_file.fish#L14
But I was resolved on master `branch` for now.

So try the master branch until the next release soon.

**Comment by joseluisq** [comment]
This issue is resolved on new release [2.3.1](https://github.com/joseluisq/gitnow/releases/tag/2.3.1).
