### ISSUE TITLE
alt-→ binding?

### ISSUE THREAD

**Issue by selfagency** [joseluisq/gitnow#13]
I have a weird experience using gitnow where, whenever I press `alt-→` while in my terminal, it runs a command and prevents me from navigating text. It's not in the listed keybindings so I'm not sure why.

**Comment by joseluisq** [comment]
Can you share your terminal output?
I don't have this problem. You probably need to check your terminal keybindings settings.

**Comment by joseluisq** [comment]
Additionally I plan to add support for a configuration settings which includes keybindings. See PR #15

**Comment by joseluisq** [comment]
I will close this issue due to inactivity. Feel free to open it again if it's needed.
