### ISSUE TITLE
Upgrade show command to display also diff patch

### ISSUE THREAD

**Issue by juwishmaster** [joseluisq/gitnow#15]
Replace actual command by  **`git show -p --stat  <id>`**

I thinks it's better to see what have been done.

Best regards Willy Micieli

**Comment by joseluisq** [comment]
I think that just generating a patch along with current `show` functionality makes more sense here.
For example:

```sh
~> git show --compact-summary --patch HEAD
```

With those commands in place you will get the same like `show` does now + the patch (diff of changes made) as you suggested.

**Comment by joseluisq** [comment]
Pointing out that `--patch` is `-p` (short) and  `--compact-summary` implies already `--stat`.

**Comment by juwishmaster** [comment]
i'm okay for your choise.

Best regards Willy Micieli

**Comment by joseluisq** [comment]
Done, just install from the master branch to get this change until the next release.
