### ISSUE TITLE
Send tags

### ISSUE THREAD

**Issue by juwishmaster** [joseluisq/gitnow#17]
You can also add a command **send** to push all tags.

**`git push <remote> --tags`**

Or better on all remotes using **`git remote -v`** command.

Best regard Willy Micieli

**Comment by joseluisq** [comment]
This is already managed by the `push` command because supports additional Git arguments like `--tags`.
https://github.com/joseluisq/gitnow#push

Take a look:

```sh
~> push --tags
🚀 Pushing changes...
Mode: Manual

Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/joseluisq/gitnow.git
 * [new tag]         abcdef1 -> abcdef1
 * [new tag]         abcdef2 -> abcdef2
 * [new tag]         abcdef3 -> abcdef3
```

**Comment by juwishmaster** [comment]
okay it's super !

Best regards Willy Micieli
