### ISSUE TITLE
my shell crashes when I try to install this 

### ISSUE THREAD

**Issue by matthiasdebernardini** [joseluisq/gitnow#21]
m@smolfrosty ~> fisher add joseluisq/gitnow
To completely erase z's data, remove:
/home/m/.local/share/z/data
fetching https://codeload.github.com/jethrokuan/z/tar.gz/HEAD
fetching https://codeload.github.com/jethrokuan/fzf/tar.gz/HEAD
fetching https://codeload.github.com/joseluisq/gitnow/tar.gz/HEAD
linking ~/.config/fish/functions/__z.fish
linking ~/.config/fish/functions/__z_add.fish
linking ~/.config/fish/functions/__z_clean.fish
linking ~/.config/fish/functions/__z_complete.fish
linking ~/.config/fish/conf.d/z.fish
linking ~/.config/fish/functions/__fzf_cd.fish
linking ~/.config/fish/functions/__fzf_complete.fish
linking ~/.config/fish/functions/__fzf_complete_preview.fish
linking ~/.config/fish/functions/__fzf_find_file.fish
linking ~/.config/fish/functions/__fzf_get_dir.fish
linking ~/.config/fish/functions/__fzf_open.fish
linking ~/.config/fish/functions/__fzf_parse_commandline.fish
linking ~/.config/fish/functions/__fzf_reverse_isearch.fish
linking ~/.config/fish/functions/__fzfcmd.fish
linking ~/.config/fish/conf.d/fzf.fish
linking ~/.config/fish/conf.d/fzf_key_bindings.fish
linking ~/.config/fish/functions/__gitnow_config_file.fish
linking ~/.config/fish/functions/__gitnow_functions.fish
~/.config/fish/functions/__gitnow_functions.fish (line 146): Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
    command git diff-index --quiet HEAD -- || echo "1" 2>&1
                                            ^
from sourcing file ~/.config/fish/functions/__gitnow_functions.fish
	called on line 390 of file ~/.config/fish/functions/fisher.fish

in function '_fisher_add'
	called on line 335 of file ~/.config/fish/functions/fisher.fish
	with parameter list '/home/m/.local/share/fisher/github.com/joseluisq/gitnow'

in function '_fisher_fetch'
	called on line 196 of file ~/.config/fish/functions/fisher.fish
	with parameter list 'jethrokuan/z jethrokuan/fzf joseluisq/gitnow'

in command substitution
	called on line 194 of file ~/.config/fish/functions/fisher.fish

in function '_fisher_commit'
	called on line 91 of file ~/.config/fish/functions/fisher.fish
	with parameter list 'add joseluisq/gitnow'

in function 'fisher'
	called on standard input
	with parameter list 'add joseluisq/gitnow'

linking ~/.config/fish/functions/__gitnow_manual.fish
linking ~/.config/fish/completions/__gitnow_completions.fish

below that last line it never finishes and I tried to ssh into it just now and the shell is broken

Last login: Fri Sep 11 15:48:10 2020 from 192.168.178.171
~/.config/fish/functions/__gitnow_functions.fish (line 146): Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
    command git diff-index --quiet HEAD -- || echo "1" 2>&1
                                            ^
from sourcing file ~/.config/fish/functions/__gitnow_functions.fish
	called on line 13 of file ~/.config/fish/conf.d/gitnow_config.fish

from sourcing file ~/.config/fish/conf.d/gitnow_config.fish
	called on line 250 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
	called during startup

source: Error while reading file '/home/m/.config/fish/functions/__gitnow_functions.fish'

**Comment by joseluisq** [comment]
Please take a look if you are not using an old Fish shell version.

https://github.com/fish-shell/fish-shell/issues/5582#issuecomment-457286645

**Comment by matthiasdebernardini** [comment]
Yea I was using old version of fish. My bad.
