### ISSUE TITLE
Extend tag command for annotated Tags

### ISSUE THREAD

**Issue by lukasgierth** [joseluisq/gitnow#41]
Would it be useful to add the `-a` flag optional to the `tag` command to create the SemVer Tag as an annotated tag?

**Comment by joseluisq** [comment]
Sure, maybe adding a `-a  --annotate` to the `tag` flags list.

**Comment by lukasgierth** [comment]
You want to use `-a` in the not yet implemented `--premajor`, so that would be a naming conflict. Which should we rename?

I created a pull request, that uses a quite generic implementation so we could add other arguments later on.

**Comment by joseluisq** [comment]
> You want to use `-a` in the not yet implemented `--premajor`, so that would be a naming conflict. Which should we rename?
> 
> I created a pull request, that uses a quite generic implementation so we could add other arguments later on.

It's not really a problem since `--premajor` is not implemented yet and it could be changed to something else if needed.
