### ISSUE TITLE
cause little bit of slow startup of fish

### ISSUE THREAD

**Issue by touhidulshawan** [joseluisq/gitnow#45]
I am getting little of bit slow startup of fish when I launched the Terminal because of the is plugin. Is there any solution?

**Comment by joseluisq** [comment]
Probably because of the config file reading process which happens at startup time.

You want to take a look at https://github.com/joseluisq/gitnow/issues/23 and so you can provide here more insights about your issue.

**Comment by touhidulshawan** [comment]
Solved. Thanks 🙂
